### ISSUE TITLE
Update Play Core Library for Android 14 Compatibility

### ISSUE THREAD

**Issue by HarshitMadhav** [MinaSamir11/react-native-in-app-review#175]
Firstly, thank you for this package @MinaSamir11  and the maintainers!

**Issue Description:**
There is an important compatibility issue with the current version of the Play Core library (com.google.android.play:core) and the upcoming Android 14 (targetSdkVersion 34).

**Problem:**
Google has introduced a backwards-incompatible change to broadcast receivers in Android 14 to improve user security. As a result, the current version of the Play Core library (core:1.9.0) is incompatible with targetSdkVersion 34. This incompatibility will cause crashes and other issues in apps targeting Android 14.

**Impact:**
Target SDK Requirement: From August 31, Google Play requires all new app releases to target Android 14.
**Release Block**: Apps using the current version of the Play Core library will not be able to release future versions to production or open testing.
**User Security:** The security improvements in Android 14 are crucial for user protection, and maintaining compatibility is essential.

**Required Action:**
Please update the Play Core Maven dependency to an Android 14 compatible version. This will ensure that applications using this library can continue to be released on the Google Play Store without any issues.

Reference:
[Play Core Migration Guide](https://developer.android.com/guide/playcore#playcore-migration)

**Comment by HarshitMadhav** [comment]
Pull Request raised for this fix here
[https://github.com/MinaSamir11/react-native-in-app-review/pull/176](https://github.com/MinaSamir11/react-native-in-app-review/pull/176)

**Comment by Durkaen** [comment]
same here

![Screenshot 2024-06-21 at 11 41 12](https://github.com/MinaSamir11/react-native-in-app-review/assets/13126062/d50c183b-3276-4f46-9394-3450cd47a2b8)

**Comment by HarshitMadhav** [comment]
@Durkaen you can use the fix as I have added in the PR

**Comment by MinaSamir11** [comment]
I will check out ur pull request.

**Comment by MinaSamir11** [comment]
@Durkaen It seems that you are using the previous version, please checkout and mention your installed in-app-review version & update it to the latest version. 

Thanks

**Comment by HarshitMadhav** [comment]
@MinaSamir11 I am running on 4.3.3v

**Comment by miladdev85** [comment]
What is the current status of this? Will it get merged and released?

**Comment by manualexSP** [comment]
Hey guys, I'm having the same issues as well, any news? I noticed that the PR created for this issue was closed.

**Comment by MinaSamir11** [comment]
> Hey guys, I'm having the same issues as well, any news? I noticed that the PR created for this issue was closed.
> 
> 

Already fixed in the latest version 4.3.3 &
please checkout if you're using another lib already using play core.

**Comment by manualexSP** [comment]
Yeah, it's all good :D Google mentioned a list of versions and I didn't notice that the current version is not on that list  😭

**Comment by talharasool** [comment]
@HarshitMadhav Hey guys I am on the latest version but still facing issue in android. In the console it shows that it's working but the popup didn’t appear in debug mode and internal testing any solution for it?

**Comment by MinaSamir11** [comment]
> @HarshitMadhav @MinaSamir11  Hey guys I am on the latest version but still facing issue in android. In the console it shows that it's working but the popup didn’t appear in debug mode and internal testing any solution for it?

Please read well the readme file, to solve your issue.

**Comment by Durkaen** [comment]
> @Durkaen It seems that you are using the previous version, please checkout and mention your installed in-app-review version & update it to the latest version.
> 
> Thanks

Oh my bad, sorry. I've upgraded to the latest version now, everything's fine. :)

**Comment by nl-danish** [comment]
I'm a little confused,

Are we supposed to upgrade this packaged to the latest 4.3.3? Or, are we supposed to use this [fix](https://github.com/MinaSamir11/react-native-in-app-review/pull/176)

Can anybody please guide? Thank you so much.

**Comment by MinaSamir11** [comment]
> I'm a little confused,
> 
> 
> 
> Are we supposed to upgrade this packaged to the latest 4.3.3? Or, are we supposed to use this [fix](https://github.com/MinaSamir11/react-native-in-app-review/pull/176)
> 
> Because in the latest commit, it seems that the package have removed the play core dependency and are not moving forward with it ([reference](https://github.com/MinaSamir11/react-native-in-app-review/commit/85576fba74cd13b7eec6b784b9ddc8f45f98c6fb))
> 
> 
> 
> Can anybody please guide? Thank you so much.

Did you follow the captain instructions or the passenger in the plane 😄 
do not be confused this commit means nothing, it isn't affect on any thing in the package. 

**use the latest version.**

Have a nice day.

**Comment by nl-danish** [comment]
@MinaSamir11 
haha, good example.

thank you, have a nice day to you too.
