### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by wontone18** [MinaSamir11/react-native-in-app-review#7]
Hi i am using and invoke this in react hook

```
 useEffect(() => {
   // _referalid();
	 InAppReview.RequestInAppReview();
	
  }, []);
```

But its not working at all.

**Comment by MinaSamir11** [comment]
Read this carefully 👍 for testing =>
Test using an internal test track:
Upload your app to the internal test track and install it on a device with a user account that has access to the internal test track. When using an internal test track, the following conditions must be met:

1 - The user account in the Play Store has downloaded the app from the Play Store. When this is the case, the app is listed in the user's Google Play library.
2- The user does not currently have a review for the app.
3- The quota has not been reached.

After the account on the device has downloaded the app at least once from the internal test track and is part of the testers list, you can deploy new versions of the app locally to that device (for example, using Android Studio).

RECOMMENDED: Test using internal app sharing:
Alternatively, for rapid iteration you can use internal app sharing to test your integration. This method lets you quickly test changes by skipping some of the verification that happens with other test tracks.

Important: When using an app installed with internal app sharing, reviews can't be submitted. To emphasize this difference, the button is disabled in the UI.

OR Publish your new release to production after integration, to trigger UI
without one of 3 options above, UI will not triggered.

**Comment by MinaSamir11** [comment]
Read this carefully 👍 for testing =>
Test using an internal test track:
Upload your app to the internal test track and install it on a device with a user account that has access to the internal test track. When using an internal test track, the following conditions must be met:

1 - The user account in the Play Store has downloaded the app from the Play Store. When this is the case, the app is listed in the user's Google Play library.
2- The user does not currently have a review for the app.
3- The quota has not been reached.

After the account on the device has downloaded the app at least once from the internal test track and is part of the testers list, you can deploy new versions of the app locally to that device (for example, using Android Studio).

**_RECOMMENDED_**: Test using internal app sharing:
Alternatively, for rapid iteration you can use internal app sharing to test your integration. This method lets you quickly test changes by skipping some of the verification that happens with other test tracks.

Important: When using an app installed with internal app sharing, reviews can't be submitted. To emphasize this difference, the button is disabled in the UI.
________________________________________________________________
+ OR Publish your new release to production after integration, to trigger UI 

 **without one of 3 options above, UI will not triggered.**

**Comment by wontone18** [comment]
lol i already have done these above points. but your module is not working.

**Comment by MichaelAmadheo** [comment]
Hello, is there any way to trigger the in App review without having to publish it on Play Store?

**Comment by wontone18** [comment]
one more thing , you should change your gradle version also 29.0.0.

**Comment by MinaSamir11** [comment]
please give me info. about your testing environment, and version of your projects, and any error displayed if exist, to help you. 
Check if you are testing in production make sure that your account have not reviewed your app on play store. 

-gradle version note: TODO task. will be in next npm version. Thanks

**Comment by MinaSamir11** [comment]
@MichaelAmadheo you can test it without publish new release to store.
Read the following comment to see how you can test with Test using internal app sharing || Test using an internal test track:
[](https://github.com/MinaSamir11/react-native-in-app-review/issues/7#issuecomment-701162534)

**Comment by wontone18** [comment]
> please give me info. about your testing environment, and version of your projects, and any error displayed if exist, to help you.
> Check if you are testing in production make sure that your account have not reviewed your app on play store.
> 
> -gradle version note: TODO task. will be in next npm version. Thanks

ok i will wait for your most updated gradle version.

**Comment by MinaSamir11** [comment]
> > please give me info. about your testing environment, and version of your projects, and any error displayed if exist, to help you.
> > Check if you are testing in production make sure that your account have not reviewed your app on play store.
> > -gradle version note: TODO task. will be in next npm version. Thanks
> 
> ok i will wait for your most updated gradle version.

Check it now.

**Comment by wontone18** [comment]
> > > please give me info. about your testing environment, and version of your projects, and any error displayed if exist, to help you.
> > > Check if you are testing in production make sure that your account have not reviewed your app on play store.
> > > -gradle version note: TODO task. will be in next npm version. Thanks
> > 
> > 
> > ok i will wait for your most updated gradle version.
> 
> Check it now.

**The specified Android SDK Build Tools version (29.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1**

same that error nothing change gradle error.

**Comment by wontone18** [comment]
you should change from your build.gradle 

```
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.0"
```

**Comment by MinaSamir11** [comment]
> you should change from your build.gradle
> 
> ```
> android {
>     compileSdkVersion 29
>     buildToolsVersion "29.0.0"
> ```

Solved Now ?

**Comment by MinaSamir11** [comment]
> > > > please give me info. about your testing environment, and version of your projects, and any error displayed if exist, to help you.
> > > > Check if you are testing in production make sure that your account have not reviewed your app on play store.
> > > > -gradle version note: TODO task. will be in next npm version. Thanks
> > > 
> > > 
> > > ok i will wait for your most updated gradle version.
> > 
> > 
> > Check it now.
> 
> **The specified Android SDK Build Tools version (29.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1**
> 
> same that error nothing change gradle error.

Solved Now ?

**Comment by wontone18** [comment]
> > > > > please give me info. about your testing environment, and version of your projects, and any error displayed if exist, to help you.
> > > > > Check if you are testing in production make sure that your account have not reviewed your app on play store.
> > > > > -gradle version note: TODO task. will be in next npm version. Thanks
> > > > 
> > > > 
> > > > ok i will wait for your most updated gradle version.
> > > 
> > > 
> > > Check it now.
> > 
> > 
> > **The specified Android SDK Build Tools version (29.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1**
> > same that error nothing change gradle error.
> 
> Solved Now ?

:) no its not solved. you are still using a older version of a gradle 
 compileSdkVersion 29
    buildToolsVersion "29.0.0"

you should update this with a latest version.

**Comment by wontone18** [comment]
> > > > > please give me info. about your testing environment, and version of your projects, and any error displayed if exist, to help you.
> > > > > Check if you are testing in production make sure that your account have not reviewed your app on play store.
> > > > > -gradle version note: TODO task. will be in next npm version. Thanks
> > > > 
> > > > 
> > > > ok i will wait for your most updated gradle version.
> > > 
> > > 
> > > Check it now.
> > 
> > 
> > **The specified Android SDK Build Tools version (29.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1**
> > same that error nothing change gradle error.
> 
> Solved Now ?

i can see you are having a latest version. let me review it. But i will tell you my test result on monday.

**Comment by wontone18** [comment]
> > > > > please give me info. about your testing environment, and version of your projects, and any error displayed if exist, to help you.
> > > > > Check if you are testing in production make sure that your account have not reviewed your app on play store.
> > > > > -gradle version note: TODO task. will be in next npm version. Thanks
> > > > 
> > > > 
> > > > ok i will wait for your most updated gradle version.
> > > 
> > > 
> > > Check it now.
> > 
> > 
> > **The specified Android SDK Build Tools version (29.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1**
> > same that error nothing change gradle error.
> 
> Solved Now ?

what's your jdk version?

**Comment by danielvportlandia** [comment]
I thought it was broken too at first on Android but after reviewing the troubleshooting docs ([https://developer.android.com/guide/playcore/in-app-review/test](https://developer.android.com/guide/playcore/in-app-review/test)) I realized that I was not using the primary Google account set on my device. To fix, go to Settings => Google => at the top hit the dropdown => select an account to be your primary, then ensure that you download the app with your set primary account. After doing that it popped up on my first try.

**Comment by komelabbbas** [comment]
In Android it working Fin, But in iOS TestFlight app  modal not showing..?

import InAppReview from 'react-native-in-app-review';

> try {
>   const isAvailable = await InAppReview.isAvailable();

>  if (!isAvailable) {
           return;
> }

>  InAppReview.RequestInAppReview();
>} catch (e) {}


how can I test app in TestFlight build..?
it is work in real time App Store production..?

**Comment by MinaSamir11** [comment]
> In Android it working Fin, But in iOS TestFlight app modal not showing..?
> 
> import InAppReview from 'react-native-in-app-review';
> 
> > try {
> > const isAvailable = await InAppReview.isAvailable();
> 
> > if (!isAvailable) {
> > return;
> > }
> 
> > InAppReview.RequestInAppReview();
> > } catch (e) {}
> 
> how can I test app in TestFlight build..?
> it is work in real time App Store production..?

This issue resolved here .
https://github.com/MinaSamir11/react-native-in-app-review/issues/17#issuecomment-742796931

**Comment by rb162215** [comment]
I am not able so see popup in my android app, after download it from playstore

**Comment by hotaryuzaki** [comment]
> I thought it was broken too at first on Android but after reviewing the troubleshooting docs (https://developer.android.com/guide/playcore/in-app-review/test) I realized that I was not using the primary Google account set on my device. To fix, go to Settings => Google => at the top hit the dropdown => select an account to be your primary, then ensure that you download the app with your set primary account. After doing that it popped up on my first try.

is it work if we install from APK??
my prod apps already in Play store, so if check Play store already detect it is installed.
But still pop up not showing

**Comment by MinaSamir11** [comment]
> i already tried danielvportlandia solution

You have to upload new bundle to play store after integrate with package, and popup will be display. Did you try that ?

**Comment by johansmith** [comment]
Hello friend, thanks for your plugin, I am testing directly from the terminal with npm run android to a physical device, but it does not work. Should I upload a trial version to the PLAY STORE? Or with testing the android npm run should it work?

**Comment by MinaSamir11** [comment]
you have to upload it to play store or use on of testing track 
see this: https://github.com/MinaSamir11/react-native-in-app-review/issues/6#issuecomment-699482016

**Comment by mrifat1** [comment]
Hello, I used this in app review library on our development server. The app is running on play store but we are testing on development server. the problem I'm facing that, after clicking the button that redirect to "InAppReview.RequestInAppReview" is not working. It worked for the first time after implementing. Then it's not working. I mean after clicking the button, The UI is not popping up.

**Comment by MinaSamir11** [comment]
iOS or android ?

**Comment by mrifat1** [comment]
android 
I ran using npx react-native run-android

**Comment by mrifat1** [comment]
I also tried the "example part" of your repo to run or at least popping up the UI. That was not popping up too. The same code, didn't change anything.

**Comment by MinaSamir11** [comment]
please read ReadMe well

**Comment by MinaSamir11** [comment]
to test integration it will not work on development phase . you have to to read section of readMe to test popup
